### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Getquanty/gtm-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.site_id when generating the url
const url = 'https://get.smart-data-systems.com/gq?consent='+consent+'&notrack='+notrack+'&site_id='+data.site_id;
2) The documentation [url](https://getquanty.zendesk.com/hc/fr/articles/360016082693-Installer-le-script-GetQuanty-via-Google-Tag-Manager-GTM-) mentioned in the metadata fil is behind a login page. Please provide a valid url.
![Screenshot 2021-09-10 1 23 37 PM](https://user-images.githubusercontent.com/53495700/132913702-a5a3a0f3-084e-4c59-b874-a40a6c6807b3.png)

**Comment by vg-getquanty** [comment]
Hi,

Thanks for your message.

We can't use **encodeUriComponent** (see attachment) in Tag Manager, but **data.site_id** is only a string of numbers. This precision should allow you to validate this configuration model, I hope.

![image](https://user-images.githubusercontent.com/83222969/141125847-151ef183-fa97-4602-9331-830ad0dfb073.png)


We have also updated the documentation on a public link : https://www.getquanty.com/wp-content/uploads/2021/11/Installer-le-script-GetQuanty-via-Google-Tag-Manager-GTM-–-GetQuanty.pdf

Best regards,
Valentin from GetQuanty
